spring.application.name: boxfish-recommend-provider

logging:
  file: ${user.home}/logs/${spring.application.name}.log
  level:
    org.springframework: INFO
    com.boxfishedu: DEBUG
#    org.springframework.data.mongodb: DEBUG

server.port: 8002

spring.jpa:
  show-sql: true
#  generate-ddl: true
#  hibernate.ddl-auto: update
  database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
  hibernate.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

spring.datasource:
  driver-class-name: com.mysql.jdbc.Driver
  test-while-idle: true
  validation-query: SELECT 1
  initial-size: 2
  max-active: 50
  max-idle: 20

boxfish.recommend.illegalVersion:
  - 7.0.0.RELEASE.AppStore


spring.profiles.active: production

---
spring.profiles: production


spring.datasource:
  url: jdbc:mysql://boxfishdb2013.mysql.rds.aliyuncs.com/bebase?useUnicode=true&characterEncoding=utf8
  username: recommend2016
  password: VhGseejEWfdBXybx6nfH7MLNvPwAtrwH

spring.data.mongodb:
  database: beqp
  host: mongo.db.boxfish.cn
  username: bebase
  password: boxfish

---
spring.profiles: preproduction


spring.datasource:
  url: jdbc:mysql://boxfish2016outside.mysql.rds.aliyuncs.com/bebase?useUnicode=true&characterEncoding=utf8
  username: recommend
  password: Boxfishheziyu

spring.data.mongodb:
  database: beqp
  host: mongo.db.boxfish.cn
  username: bebase
  password: boxfish

---
spring.profiles: development


spring.datasource:
  url: jdbc:mysql://192.168.0.100?useUnicode=true&characterEncoding=utf8
  username: bebase
  password: boxfish

spring.data.mongodb:
  database: beqp
  host: 192.168.0.100
  username: bebase
  password: boxfish
